import archiver from 'archiver';

const DS_PROFILES = {
  material: {
    name: 'Material UI',
    deps: {
      '@mui/material': '^5.16.0',
      '@mui/icons-material': '^5.16.0',
      '@emotion/react': '^11.11.0',
      '@emotion/styled': '^11.11.0',
    },
    cssImports: [],
  },
  ant: {
    name: 'Ant Design',
    deps: { antd: '^5.20.0', '@ant-design/icons': '^5.4.0' },
    cssImports: [],
  },
  carbon: {
    name: 'IBM Carbon',
    deps: {
      '@carbon/react': '^1.71.0',
      '@carbon/styles': '^1.71.0',
      '@carbon/icons-react': '^11.51.0',
    },
    cssImports: ['@carbon/styles/css/styles.css'],
  },
  chakra: {
    name: 'Chakra UI',
    deps: {
      '@chakra-ui/react': '^2.10.0',
      '@chakra-ui/icons': '^2.2.0',
      '@emotion/react': '^11.11.0',
      '@emotion/styled': '^11.11.0',
      'framer-motion': '^11.0.0',
    },
    cssImports: [],
  },
  mantine: {
    name: 'Mantine',
    deps: {
      '@mantine/core': '^7.17.0',
      '@mantine/hooks': '^7.17.0',
      '@tabler/icons-react': '^3.14.0',
    },
    cssImports: ['@mantine/core/styles.css'],
  },
};

const buildPackageJson = (projectName, profile) => {
  const safeName =
    projectName.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-|-$/g, '') ||
    'designforge-app';
  return JSON.stringify(
    {
      name: safeName,
      private: true,
      version: '0.1.0',
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { react: '^18.3.0', 'react-dom': '^18.3.0', ...profile.deps },
      devDependencies: { '@vitejs/plugin-react': '^4.3.0', vite: '^5.4.0' },
    },
    null,
    2,
  );
};

const VITE_CONFIG = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;

const indexHtml = (title) => `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body style="margin:0">
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;

const buildMainJsx = (cssImports) => {
  const cssLines = cssImports.map((i) => `import '${i}';`).join('\n');
  return `import React from 'react';
import { createRoot } from 'react-dom/client';
${cssLines ? cssLines + '\n' : ''}import App from './App';

createRoot(document.getElementById('root')).render(<App />);
`;
};

const buildReadme = (projectName, profile) => `# ${projectName}

Generated by **DesignForge** — a ${profile.name} React app scaffold.

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:5173.
`;

const buildGitignore = () => `node_modules
dist
.DS_Store
.env
.env.local
`;

// Stream a Vite + React project ZIP to a Next.js Response.
// Uses a TransformStream to wire archiver's Node stream → web ReadableStream.
export const buildProjectZipResponse = (project) => {
  const profile = DS_PROFILES[project.designSystem] || DS_PROFILES.material;
  const generatedCode = project.generation?.generatedCode;
  if (!generatedCode) {
    return new Response(JSON.stringify({ error: 'No generated code available' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  const safeFileName = `${project.name.replace(/\s+/g, '-')}-designforge.zip`;
  const archive = archiver('zip', { zlib: { level: 9 } });

  archive.append(buildPackageJson(project.name, profile), { name: 'package.json' });
  archive.append(VITE_CONFIG, { name: 'vite.config.js' });
  archive.append(indexHtml(project.name), { name: 'index.html' });
  archive.append(buildMainJsx(profile.cssImports), { name: 'src/main.jsx' });
  archive.append(generatedCode, { name: 'src/App.jsx' });
  archive.append(buildReadme(project.name, profile), { name: 'README.md' });
  archive.append(buildGitignore(), { name: '.gitignore' });

  const stream = new ReadableStream({
    start(controller) {
      archive.on('data', (chunk) => controller.enqueue(chunk));
      archive.on('end', () => controller.close());
      archive.on('error', (err) => controller.error(err));
      archive.finalize();
    },
  });

  return new Response(stream, {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${safeFileName}"`,
    },
  });
};
